# Generated by Django 3.0.8 on 2020-08-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=200)),
                ('categorydescription', models.CharField(blank=True, max_length=200)),
                ('categoryimg', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('name', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('discount', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('priceString', models.CharField(blank=True, max_length=200)),
                ('retailer', models.CharField(blank=True, max_length=200)),
                ('marketplace', models.CharField(blank=True, max_length=200)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('old_price', models.FloatField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('marketplaceId', models.CharField(blank=True, max_length=200)),
                ('categorymap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Categoryy')),
            ],
        ),
    ]
